// <auto-generated />
namespace YummyProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class nigimageurl2addedtoabout : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nigimageurl2addedtoabout));
        
        string IMigrationMetadata.Id
        {
            get { return "202412182101078_nig-imageurl2-added-to-about"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
